--------------------------------------------------------
--  Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "SMART_FACTORY_DB"."INVENTORY" MODIFY ("LOT_ID" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."INVENTORY" MODIFY ("LOT_NO" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."INVENTORY" MODIFY ("EXPIRATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."INVENTORY" ADD CONSTRAINT "CHK_QTY_POSITIVE" CHECK (quantity >= 0) ENABLE;
  ALTER TABLE "SMART_FACTORY_DB"."INVENTORY" ADD PRIMARY KEY ("LOT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
