REM INSERTING into SMART_FACTORY_DB.PRODUCTS
SET DEFINE OFF;
Insert into SMART_FACTORY_DB.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,UOM,SAFETY_STOCK,CATAGORY) values (3,'RM-001','พริกจินดาแห้ง','KG',100,'RAW');
Insert into SMART_FACTORY_DB.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,UOM,SAFETY_STOCK,CATAGORY) values (6,'RM-003','หอมแดง','KG',100,'RAW');
Insert into SMART_FACTORY_DB.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,UOM,SAFETY_STOCK,CATAGORY) values (7,'RM-004','น้ำตาลทราย','KG',200,'RAW');
Insert into SMART_FACTORY_DB.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,UOM,SAFETY_STOCK,CATAGORY) values (8,'RM-005','เกลือ','KG',200,'RAW');
Insert into SMART_FACTORY_DB.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,UOM,SAFETY_STOCK,CATAGORY) values (4,'RM-002','กระเทียม','KG',100,'RAW');
