--------------------------------------------------------
--  DDL for Table TRANSACTION_TYPE
--------------------------------------------------------

  CREATE TABLE "SMART_FACTORY_DB"."TRANSACTION_TYPE" 
   (	"TRS_TYPE_ID" NUMBER, 
	"TRS_TYPE_CODE" VARCHAR2(5 BYTE), 
	"TRS_TYPE_NAME" VARCHAR2(50 BYTE), 
	"ACTION_TYPE" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
