--------------------------------------------------------
--  Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTIONS" MODIFY ("TRS_ID" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTIONS" MODIFY ("TRS_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTIONS" MODIFY ("LOT_NO" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTIONS" MODIFY ("TRS_DATE" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTIONS" ADD PRIMARY KEY ("TRS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTIONS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTIONS" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
