--------------------------------------------------------
--  Constraints for Table TRANSACTION_TYPE
--------------------------------------------------------

  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTION_TYPE" MODIFY ("TRS_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTION_TYPE" MODIFY ("ACTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTION_TYPE" MODIFY ("TRS_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTION_TYPE" MODIFY ("TRS_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SMART_FACTORY_DB"."TRANSACTION_TYPE" ADD CONSTRAINT "TRANSACTION_TYPE_PK" PRIMARY KEY ("TRS_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
